function [g2g,dg2g] = autogen_g2g(xc,yc,th,a1,a2,dxc,dyc,dth,da1,da2,m1,m2,m3,I1,I2,I3,l1,l2,l3,G)
%AUTOGEN_G2G
%    [G2G,DG2G] = AUTOGEN_G2G(XC,YC,TH,A1,A2,DXC,DYC,DTH,DA1,DA2,M1,M2,M3,I1,I2,I3,L1,L2,L3,G)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    25-Mar-2016 23:25:56

t2 = sin(th);
t3 = l2.*t2.*(1.0./2.0);
t4 = a1+th;
t5 = cos(th);
t6 = l2.*t5.*(1.0./2.0);
t7 = a2-th;
t8 = m1+m2+m3;
t9 = 1.0./t8;
t10 = cos(t4);
t11 = l1.*t10.*(1.0./2.0);
t12 = t6+t11;
t13 = m1.*t12;
t14 = cos(t7);
t15 = l3.*t14.*(1.0./2.0);
t16 = t6+t15;
t17 = t13-m3.*t16;
t18 = sin(t4);
t19 = l1.*t18.*(1.0./2.0);
t20 = t3+t19;
t21 = m1.*t20;
t22 = sin(t7);
t23 = t3-l3.*t22.*(1.0./2.0);
t24 = t21-m3.*t23;
g2g = [xc-t9.*t24;yc-t9.*t17;th];
if nargout > 1
    dg2g = [dxc-dth.*t9.*t17-da1.*l1.*m1.*t9.*t10.*(1.0./2.0)-da2.*l3.*m3.*t9.*t14.*(1.0./2.0);dyc+dth.*t9.*t24+da1.*l1.*m1.*t9.*t18.*(1.0./2.0)-da2.*l3.*m3.*t9.*t22.*(1.0./2.0);dth];
end
