function [ Phi,Psi,J ] = fallingBox_contactDyn_wrapper(z,params)

p = params;
x = z(1,:);
y = z(2,:);
th = z(3,:);

% [Pc1, Pc2, Pc3] = autogen_contact_pts(x,y,th,...
%                                       p.w,p.h,...
%                                       p.m,p.I,...
%                                       p.g);
[Phi,Psi,J] = autogen_phi(x,y,th,...
                        p.w,p.h,...
                        p.m,p.I,...
                        p.g,...
                        p.line(1),p.line(2),p.line(3));

end
