function [ Phi,Psi,J ] = fallingBox_contactDyn_wrapper(z,params)

p = params;

[Pc1, Pc2, Pc3] = autogen_contact_pts(z(1,:),z(2,:),z(3,:),...
                                      p.w,p.h,...
                                      p.m,p.I,...
                                      p.g);
phi1 = pt2line_dist(Pc1,p.line);
phi2 = pt2line_dist(Pc2,p.line);
phi3 = pt2line_dist(Pc3,p.line); 

[Phi,Psi,J] = autogen_contactDyn(z(1,:),z(2,:),z(3,:),...
                                 z(4,:),z(5,:),z(6,:),...
                                 p.w,p.h,...
                                 p.m,p.I,...
                                 p.g,...
                                 p.line(1),p.line(2));
end
