function [D_mtx,C_mtx,G_vec,B_mtx] = autogen_fallingBox_EOM_mtxs(x,y,th,dx,dy,dth,w,h,m,I,g)
%AUTOGEN_FALLINGBOX_EOM_MTXS
%    [D_MTX,C_MTX,G_VEC,B_MTX] = AUTOGEN_FALLINGBOX_EOM_MTXS(X,Y,TH,DX,DY,DTH,W,H,M,I,G)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    18-Feb-2016 17:31:12

D_mtx = reshape([m,0.0,0.0,0.0,m,0.0,0.0,0.0,I],[3,3]);
if nargout > 1
    C_mtx = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
if nargout > 2
    G_vec = [0.0;g.*m;0.0];
end
if nargout > 3
    B_mtx = zeros(3,0);
end
