function [pc1,pc2,pc3] = autogen_contact_pts(x,y,th,w,h,m,I,g)
%AUTOGEN_CONTACT_PTS
%    [PC1,PC2,PC3] = AUTOGEN_CONTACT_PTS(X,Y,TH,W,H,M,I,G)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    17-Feb-2016 04:52:34

t2 = cos(th);
t3 = sin(th);
t4 = t3.*w.*(1.0./2.0);
pc1 = [x-h.*t3.*(1.0./2.0)-t2.*w.*(1.0./2.0);t4+y-h.*t2.*(1.0./2.0)];
if nargout > 1
    pc2 = [x-h.*t3.*(1.0./2.0);y-h.*t2.*(1.0./2.0)];
end
if nargout > 2
    pc3 = [x+h.*t3.*(1.0./2.0)+t2.*w.*(1.0./2.0);-t4+y+h.*t2.*(1.0./2.0)];
end
