function [Phi,Psi,J] = autogen_contactDyn(x,y,th,dx,dy,dth,w,h,m,I,g,a,c)
%AUTOGEN_CONTACTDYN
%    [PHI,PSI,J] = AUTOGEN_CONTACTDYN(X,Y,TH,DX,DY,DTH,W,H,M,I,G,A,C)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    17-Feb-2016 22:18:02

Phi = y-h.*cos(th).*(1.0./2.0);
if nargout > 1
    t2 = sin(th);
    Psi = dy+dth.*h.*t2.*(1.0./2.0);
end
if nargout > 2
    J = [0.0,1.0,h.*t2.*(1.0./2.0)];
end
