function ddq = autogen_fallingBox_ddq(x,y,th,dx,dy,dth,l,w,h,m,I,g,a,c)
%AUTOGEN_FALLINGBOX_DDQ
%    DDQ = AUTOGEN_FALLINGBOX_DDQ(X,Y,TH,DX,DY,DTH,L,W,H,M,I,G,A,C)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    14-Mar-2016 18:51:21

ddq = [0.0;(l-g.*m)./m;(h.*l.*sin(th).*(1.0./2.0))./I];
