function pc1 = autogen_contact_pts(x,y,th,w,h,m,I,g)
%AUTOGEN_CONTACT_PTS
%    PC1 = AUTOGEN_CONTACT_PTS(X,Y,TH,W,H,M,I,G)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    23-Mar-2016 14:30:17

pc1 = [x+h.*sin(th).*(1.0./2.0);y-h.*cos(th).*(1.0./2.0)];
