function [Phi,Psi,J] = autogen_contactDyn(x,y,th,dx,dy,dth,w,h,m,I,g)
%AUTOGEN_CONTACTDYN
%    [PHI,PSI,J] = AUTOGEN_CONTACTDYN(X,Y,TH,DX,DY,DTH,W,H,M,I,G)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    23-Mar-2016 14:30:18

t2 = cos(th);
t3 = sin(th);
Phi = [y-h.*t2.*(1.0./2.0);y-h.*t2.*(1.0./2.0)-t3.*w.*(1.0./2.0);y-h.*t2.*(1.0./2.0)+t3.*w.*(1.0./2.0)];
if nargout > 1
    t4 = h.*t3.*(1.0./2.0);
    t5 = t2.*w.*(1.0./2.0);
    t6 = t4+t5;
    Psi = [dy+dth.*h.*t3.*(1.0./2.0);dy+dth.*(t4-t2.*w.*(1.0./2.0));dy+dth.*t6];
end
if nargout > 2
    J = reshape([0.0,0.0,0.0,1.0,1.0,1.0,t4,t4-t5,t6],[3,3]);
end
