function ddq = autogen_fallingBox_ddq(x,y,th,dx,dy,dth,l1,l2,l3,w,h,m,I,g)
%AUTOGEN_FALLINGBOX_DDQ
%    DDQ = AUTOGEN_FALLINGBOX_DDQ(X,Y,TH,DX,DY,DTH,L1,L2,L3,W,H,M,I,G)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    23-Mar-2016 14:30:17

t2 = cos(th);
t3 = sin(th);
ddq = [0.0;(l1+l2+l3-g.*m)./m;(h.*l1.*t3.*(1.0./2.0)+h.*l2.*t3.*(1.0./2.0)+h.*l3.*t3.*(1.0./2.0)-l2.*t2.*w.*(1.0./2.0)+l3.*t2.*w.*(1.0./2.0))./I];
