function [g1,g2,g3,h1,h2,h3,f1,f2,f3,g] = autogen_kinematics(x,y,th,a1,a2,m1,m2,m3,I1,I2,I3,l1,l2,l3,G)
%AUTOGEN_KINEMATICS
%    [G1,G2,G3,H1,H2,H3,F1,F2,F3,G] = AUTOGEN_KINEMATICS(X,Y,TH,A1,A2,M1,M2,M3,I1,I2,I3,L1,L2,L3,G)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    25-Mar-2016 18:51:46

t2 = a1+th;
t3 = sin(th);
t4 = l2.*t3.*(1.0./2.0);
t5 = cos(th);
t6 = l2.*t5.*(1.0./2.0);
t7 = a2-th;
t8 = sin(t7);
t9 = cos(t7);
t10 = -a2+th;
t11 = sin(t2);
t12 = cos(t2);
t13 = t4+x;
t14 = t6+y;
t15 = -t4+x;
t16 = -t6+y;
t17 = l3.*t8.*(1.0./2.0);
t18 = -t4+t17+x;
t19 = l1.*t11.*(1.0./2.0);
t20 = t4+t19+x;
t21 = m1+m2+m3;
t22 = 1.0./t21;
t23 = l1.*t12.*(1.0./2.0);
t24 = t6+t23+y;
g1 = [t20;t24;t2];
if nargout > 1
    g2 = [x;y;th];
end
if nargout > 2
    g3 = [t18;-t6+y-l3.*t9.*(1.0./2.0);t10];
end
if nargout > 3
    h1 = [t13;t14;t2];
end
if nargout > 4
    h2 = [t15;t16;th];
end
if nargout > 5
    h3 = [-t4+x+l3.*t8;-t6+y-l3.*t9;t10];
end
if nargout > 6
    f1 = [t4+x+l1.*t11;t6+y+l1.*t12;t2];
end
if nargout > 7
    f2 = [t13;t14;th];
end
if nargout > 8
    f3 = [t15;t16;t10];
end
if nargout > 9
    g = [t22.*(m1.*t20+m3.*t18+m2.*x);t22.*(m1.*t24+m2.*y-m3.*(t6-y+l3.*t9.*(1.0./2.0)));th];
end
