function [dg1,dg2,dg3,dh1,dh2,dh3,df1,df2,df3,dg] = autogen_velocities(x,y,th,a1,a2,dx,dy,dth,da1,da2,m1,m2,m3,I1,I2,I3,l1,l2,l3,G)
%AUTOGEN_VELOCITIES
%    [DG1,DG2,DG3,DH1,DH2,DH3,DF1,DF2,DF3,DG] = AUTOGEN_VELOCITIES(X,Y,TH,A1,A2,DX,DY,DTH,DA1,DA2,M1,M2,M3,I1,I2,I3,L1,L2,L3,G)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    25-Mar-2016 18:51:47

t2 = a1+th;
t3 = cos(t2);
t4 = sin(t2);
t5 = cos(th);
t6 = l2.*t5.*(1.0./2.0);
t7 = a2-th;
t8 = cos(t7);
t9 = sin(th);
t10 = l2.*t9.*(1.0./2.0);
t11 = sin(t7);
t12 = da1+dth;
t13 = dth.*l2.*t5.*(1.0./2.0);
t14 = -da2+dth;
t15 = dx+t13;
t16 = dth.*l2.*t9.*(1.0./2.0);
t17 = dx-t13;
t18 = dy+t16;
t19 = l1.*t3.*(1.0./2.0);
t20 = t6+t19;
t21 = l3.*t8.*(1.0./2.0);
t22 = t6+t21;
t23 = m1+m2+m3;
t24 = 1.0./t23;
t25 = l1.*t4.*(1.0./2.0);
t26 = t10+t25;
dg1 = [dx+dth.*t20+da1.*l1.*t3.*(1.0./2.0);dy-dth.*t26-da1.*l1.*t4.*(1.0./2.0);t12];
if nargout > 1
    dg2 = [dx;dy;dth];
end
if nargout > 2
    t27 = t10-l3.*t11.*(1.0./2.0);
    dg3 = [dx-dth.*t22+da2.*l3.*t8.*(1.0./2.0);dy+dth.*t27+da2.*l3.*t11.*(1.0./2.0);t14];
end
if nargout > 3
    dh1 = [t15;dy-dth.*l2.*t9.*(1.0./2.0);t12];
end
if nargout > 4
    dh2 = [t17;t18;dth];
end
if nargout > 5
    dh3 = [dx-dth.*(t6+l3.*t8)+da2.*l3.*t8;dy+dth.*(t10-l3.*t11)+da2.*l3.*t11;t14];
end
if nargout > 6
    df1 = [dx+dth.*(t6+l1.*t3)+da1.*l1.*t3;dy-dth.*(t10+l1.*t4)-da1.*l1.*t4;t12];
end
if nargout > 7
    df2 = [t15;dy-t16;dth];
end
if nargout > 8
    df3 = [t17;t18;t14];
end
if nargout > 9
    dg = [dx+dth.*t24.*(m1.*t20-m3.*t22)+da1.*l1.*m1.*t3.*t24.*(1.0./2.0)+da2.*l3.*m3.*t8.*t24.*(1.0./2.0);dy-dth.*t24.*(m1.*t26-m3.*t27)-da1.*l1.*m1.*t4.*t24.*(1.0./2.0)+da2.*l3.*m3.*t11.*t24.*(1.0./2.0);dth];
end
