function [p1,p2,dp1,dp2] = autogen_invPend_2DoF_kin(q1,q2,dq1,dq2,l1,l2)
%AUTOGEN_INVPEND_2DOF_KIN
%    [P1,P2,DP1,DP2] = AUTOGEN_INVPEND_2DOF_KIN(Q1,Q2,DQ1,DQ2,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    08-Feb-2016 20:03:50

t2 = sin(q1);
t3 = l1.*t2;
t4 = cos(q1);
t5 = l1.*t4;
p1 = [t3;t5];
if nargout > 1
    t6 = dq1.*l1.*t4;
    t7 = cos(q2);
    t8 = sin(q2);
    p2 = [t3+l2.*t8;t5+l2.*t7];
end
if nargout > 2
    dp1 = [t6;-dq1.*l1.*t2];
end
if nargout > 3
    dp2 = [t6+dq2.*l2.*t7;-dq1.*l1.*t2-dq2.*l2.*t8];
end
