function [U,T] = autogen_invPend_2DoF_Energy(q1,q2,dq1,dq2,l1,l2,d1,d2,m1,m2,I1,I2,g)
%AUTOGEN_INVPEND_2DOF_ENERGY
%    [U,T] = AUTOGEN_INVPEND_2DOF_ENERGY(Q1,Q2,DQ1,DQ2,L1,L2,D1,D2,M1,M2,I1,I2,G)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    08-Feb-2016 20:03:50

t4 = cos(q2);
t5 = cos(q1);
t2 = d2.*dq2.*t4+dq1.*l1.*t5;
t3 = d2.*dq2.*sin(q2)+dq1.*l1.*sin(q1);
U = dq1.^2.*(I1+d1.^2.*m1).*(1.0./2.0)+I2.*dq2.^2.*(1.0./2.0)+m2.*t2.^2.*(1.0./2.0)+m2.*t3.^2.*(1.0./2.0);
if nargout > 1
    T = g.*m2.*(d2.*t4+l1.*t5)+d1.*g.*m1.*t5;
end
