function [D_mtx,C_mtx,G_vec,B_mtx] = autogen_invPend_2DoF_EOM_mtxs(q1,q2,dq1,dq2,u1,l1,l2,d1,d2,m1,m2,I1,I2,g)
%AUTOGEN_INVPEND_2DOF_EOM_MTXS
%    [D_MTX,C_MTX,G_VEC,B_MTX] = AUTOGEN_INVPEND_2DOF_EOM_MTXS(Q1,Q2,DQ1,DQ2,U1,L1,L2,D1,D2,M1,M2,I1,I2,G)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    08-Feb-2016 20:03:50

t2 = q1-q2;
t3 = cos(t2);
t4 = d2.*l1.*m2.*t3;
D_mtx = reshape([I1+d1.^2.*m1+l1.^2.*m2,t4,t4,I2+d2.^2.*m2],[2,2]);
if nargout > 1
    t5 = sin(t2);
    C_mtx = reshape([0.0,-d2.*dq1.*l1.*m2.*t5,d2.*dq2.*l1.*m2.*t5,0.0],[2,2]);
end
if nargout > 2
    G_vec = [-g.*sin(q1).*(d1.*m1+l1.*m2);-d2.*g.*m2.*sin(q2)];
end
if nargout > 3
    B_mtx = [0.0;1.0];
end
